# A wizard walks a human through a manual procedure, step by step on Windows.
# Generated by the /wizard skill.
#
# Usage:
#   powershell -NoProfile -ExecutionPolicy Bypass -File template.ps1

$ErrorActionPreference = "Stop"

$TOTAL_STAGES = 1
$_STAGE_INDEX = 0
$ENV_FILE = if ($env:ENV_FILE) { $env:ENV_FILE } else { ".env" }
$WRITTEN_ENV = [System.Collections.Generic.List[string]]::new()
$WRITTEN_SECRET = [System.Collections.Generic.List[string]]::new()
$SKIPPED = [System.Collections.Generic.List[string]]::new()

function Clear-TerminalFrame {
    Clear-Host
}

function Show-Banner([string]$title) {
    Clear-TerminalFrame
    Write-Host "`n  $title" -ForegroundColor Cyan
    Write-Host "  $TOTAL_STAGES stages`n" -ForegroundColor DarkGray
    Write-Host "  You drive the browser; this wizard tells you exactly what to do and" -ForegroundColor DarkGray
    Write-Host "  captures the values you copy back. Stop any time with Ctrl-C.`n" -ForegroundColor DarkGray
    Pause-Step "Ready to start?"
}

function Show-Stage([string]$name) {
    Clear-TerminalFrame
    $script:_STAGE_INDEX++
    Write-Host "`n▸ Stage $script:_STAGE_INDEX/$TOTAL_STAGES · $name`n" -ForegroundColor Cyan
}

function Say([string]$msg) {
    Write-Host "  $msg"
}

function Step([string]$msg) {
    Write-Host "  • $msg" -ForegroundColor Cyan
}

function Note([string]$msg) {
    Write-Host "  $msg" -ForegroundColor DarkGray
}

function Warn([string]$msg) {
    Write-Host "  ⚠ $msg" -ForegroundColor Yellow
}

function Open-Url([string]$url) {
    Write-Host "  ↗ opening $url" -ForegroundColor Green
    Start-Process $url
}

function Pause-Step([string]$msg = "Press Enter to continue") {
    Write-Host "  $msg " -NoNewline -ForegroundColor DarkGray
    [void][System.Console]::ReadLine()
}

function Ask([string]$prompt) {
    Write-Host "  $prompt " -NoNewline -ForegroundColor White
    return [System.Console]::ReadLine()
}

function Ask-Secret([string]$prompt) {
    Write-Host "  $prompt " -NoNewline -ForegroundColor White
    $secure = Read-Host -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    return [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
}

function Write-Env([string]$key, [string]$value) {
    if (-not (Test-Path $ENV_FILE)) { New-Item -ItemType File -Path $ENV_FILE -Force | Out-Null }
    $lines = Get-Content $ENV_FILE -ErrorAction SilentlyContinue | Where-Object { $_ -notmatch "^$key=" }
    $lines += "$key=$value"
    $lines | Set-Content $ENV_FILE -Encoding UTF8
    $WRITTEN_ENV.Add($key)
    Write-Host "  ✓ wrote $key → $ENV_FILE" -ForegroundColor Green
}

function Finish-Wizard {
    Clear-TerminalFrame
    Write-Host "`n  ✓ Setup complete`n" -ForegroundColor Green
    if ($WRITTEN_ENV.Count -gt 0) { Note "wrote $($WRITTEN_ENV.Count) value(s) to $ENV_FILE: $($WRITTEN_ENV -join ', ')" }
    if ($WRITTEN_SECRET.Count -gt 0) { Note "set $($WRITTEN_SECRET.Count) secret(s): $($WRITTEN_SECRET -join ', ')" }
    if ($SKIPPED.Count -gt 0) {
        Write-Host "`n  Still to do by hand:" -ForegroundColor Yellow
        foreach ($s in $SKIPPED) { Note "  - $s" }
    }
    Write-Host ""
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One Show-Stage per step.
# ──────────────────────────────────────────────────────────────────────────

$TOTAL_STAGES = 1
Show-Banner "Stripe setup"

Show-Stage "Stripe: API keys"
Say "We'll grab your Stripe test keys and store them for local dev + CI."
Open-Url "https://dashboard.stripe.com/test/apikeys"
Step "On the API keys page, copy the Publishable key (starts pk_test_)."
$pubKey = Ask "Paste the publishable key:"
Step "Click 'Reveal test key' on the Secret key row, then copy it."
$secKey = Ask-Secret "Paste the secret key:"

Write-Env "STRIPE_PUBLISHABLE_KEY" $pubKey
Write-Env "STRIPE_SECRET_KEY" $secKey

Finish-Wizard
