import sys
import utils

def run(args):
    print("=====================================================================")
    print("   🚀 Welcome to Antigravity Agent Core Onboarding Guide 🚀")
    print("=====================================================================")
    print("Antigravity Agent Core (AAC) is a developer protocol and workspace")
    print("layout designed to coordinate human-agent pair-programming safely,")
    print("cost-effectively, and securely.")
    print("")
    print("---------------------------------------------------------------------")
    print("💡 THE 3-STEP DAILY WORKFLOW FOR DEVELOPERS & AGENTS")
    print("---------------------------------------------------------------------")
    print("When modifying code in this workspace, follow this atomic sequence:")
    print("")
    print("1. LOCK the module you want to edit:")
    print("   $ ./.agents/scripts/helper.sh lock <module-directory>")
    print("   Example: ./.agents/scripts/helper.sh lock cli")
    print("   (This tells other developers/agents not to modify this module.)")
    print("")
    print("2. WRITE your code and tests (TDD is highly recommended).")
    print("")
    print("3. COMMIT your changes using the helper commit command:")
    print("   $ ./.agents/scripts/helper.sh commit <type> <scope> \"description\" [files...]")
    print("   Example: ./.agents/scripts/helper.sh commit feat cli \"add push subcommand\"")
    print("   (This runs validation checks, rotates SSH keys/Git profiles, commits,")
    print("   and automatically releases your lock).")
    print("")
    print("---------------------------------------------------------------------")
    print("🩺 KEY DIAGNOSTICS & SYSTEM COMMANDS")
    print("---------------------------------------------------------------------")
    print("- Run Health Checks: ./.agents/scripts/helper.sh doctor")
    print("  (Checks Git hooks, execution permissions, and workspace validation status.)")
    print("")
    print("- Validate Compliance: ./.agents/scripts/helper.sh validate")
    print("  (Audits workspace for hardcoded secrets, environment purity, and budget limits.)")
    print("")
    print("- Setup Profile Rotation: ./.agents/scripts/helper.sh git-profile")
    print("  (Manages multiple local git config identities and rotates SSH key bindings.)")
    print("")
    print("---------------------------------------------------------------------")
    print("📚 DOCUMENTATION & RESOURCES")
    print("---------------------------------------------------------------------")
    print("Detailed guides are located inside the root 'docs/' directory:")
    print("- Setup Guide:        docs/setup_guide.md")
    print("- CLI Reference:      docs/cli_guide.md")
    print("- Agent Workflows:    docs/agent_workflow.md")
    print("- Directory Layout:   docs/directory_blueprint.md")
    print("=====================================================================")
